### PR TITLE
Cache Inkpads for 60 seconds

### PR DESCRIPTION
**Pull request by larskluge**
cc/ @mondoreale What do you think of this approach?

### CODE REVIEW

**Comment by mondoreale** [comment]
Looking good. I like the idea or wrapping `node-inkpad` so it behaves like before but is faster.

**Comment by mondoreale** [comment]
Also, what do you think about… integrating your cache mechanism into node-inkpad directly? You'd then call `node-inkpad` more or less like this?
```javascript
require('node-inkpad')('id', …, 'id', { cache: true }).then(…)
```

**Comment by larskluge** [comment]
Thought about it too, but decided against it for "today". 

I think it would be a great addition for `node-inkpad` ! :)

**Comment by mondoreale** [comment]
Will introduce it sometime soon. :)

**Pull request merged**
